# Use root/example as user/password credentials
version: '3.1'

services:
    app:
        build: ./store-api
        restart: always
        environment:
        - CONNECT_TO_DATABASE=1
        - MYSQL__HOSTNAME=db
        - MYSQL__PORT=3306
        - MYSQL__USERNAME=webapp
        - MYSQL__PASSWORD=webbapp_secret_password
        - MYSQL__DATABASE=storefront
        - JWT_SECRET_KEY=d005cf783bde584a9106853f2ab04dc859031b051f3a2e7de3ee46e30a8b0008
        - JWT_ALGORITHM=HS256
        ports:
        - "8000:8000"
        expose:
        - 8000

    db:
        image: mysql
        # command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
        - MYSQL_ROOT_PASSWORD=my_secret_password
        - MYSQL_DATABASE=storefront
        - MYSQL_USER=webapp
        - MYSQL_PASSWORD=webbapp_secret_password
        ports: 
        - "3306:3306"
        - "33060:33060"
        volumes:
        - dbdata:/var/lib/mysql
        # Useless: - ./mysql-init:/docker-entrypoint-initdb.d

 #   adminer:
 #       image: adminer
 #       restart: always
 #       ports:
 #       - 8080:8080
 #       expose:
 #       - 8080

volumes:
    dbdata: